import "./globals.css";
import NavBar from "./navbar/page";
import Footer from "./footer/page";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body suppressHydrationWarning={true}>
        <header>
          <NavBar />
        </header>
        {children}

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
